// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'carousel': string;
  'carousel__header': string;
  'carousel__inside': string;
  'carousel__rail': string;
  'carousel__rail-trigger': string;
  'gallery': string;
  'gallery__figure': string;
  'gallery__figure-img': string;
  'gallery__inside': string;
  'gallery__trigger': string;
  'is-active': string;
  'is-left': string;
  'is-loading': string;
  'is-right': string;
}
export const cssExports: CssExports;
export default cssExports;
