#!/bin/bash

#COMMANDS
# ./toolkit setup
# ./toolkit git-commit
# ./toolkit generate-component

# ./toolkit setup
if [ "$1" = "setup" ]; then
    eval "sh .scripts/$1"

# ./toolkit git-commit
elif [ "$1" = "git-commit" ]; then
    eval "sh .scripts/$1"

elif [ "$1" = "generate-component" ]; then
    eval "sh .scripts/$1"
fi
