// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'is-active': string;
  'modal': string;
  'modal__window': string;
  'modal__window-inside': string;
}
export const cssExports: CssExports;
export default cssExports;
