// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button__inside': string;
  'is-block': string;
  'is-dark': string;
  'is-inline': string;
  'is-light': string;
  'is-primary': string;
  'is-secondary': string;
}
export const cssExports: CssExports;
export default cssExports;
