// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'form__field': string;
  'form__input': string;
  'form__label': string;
  'form__textarea': string;
  'form__validation': string;
  'is-hidden': string;
}
export const cssExports: CssExports;
export default cssExports;
