// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'is-align-center': string;
  'is-align-container': string;
  'is-align-left': string;
  'is-align-right': string;
}
export const cssExports: CssExports;
export default cssExports;
