// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'is-logo-1': string;
  'is-logo-2': string;
  'is-logo-3': string;
  'logo': string;
}
export const cssExports: CssExports;
export default cssExports;
