// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'video': string;
  'video__media': string;
}
export const cssExports: CssExports;
export default cssExports;
