// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'text-align-center': string;
  'text-align-left': string;
  'text-align-right': string;
  'text-lrg-align-center': string;
  'text-lrg-align-left': string;
  'text-lrg-align-right': string;
  'text-med-align-center': string;
  'text-med-align-left': string;
  'text-med-align-right': string;
  'text-sml-align-center': string;
  'text-sml-align-left': string;
  'text-sml-align-right': string;
  'text-xlrg-align-center': string;
  'text-xlrg-align-left': string;
  'text-xlrg-align-right': string;
  'text-xxlrg-align-center': string;
  'text-xxlrg-align-left': string;
  'text-xxlrg-align-right': string;
}
export const cssExports: CssExports;
export default cssExports;
