// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accordion': string;
  'accordion__item': string;
  'accordion__reveal': string;
  'accordion__trigger': string;
  'is-visible': string;
}
export const cssExports: CssExports;
export default cssExports;
